env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[c4a87685e90a7d689c53cef6cdf364f9d3425980bad627b9d434b4621108ce3c2432e439b2c2caf9b317bccdc6447115]"


task:
    name: Buildbouuut
    timeout_in: 122m
    container:
      image: mrkhan007/aosp:latest
      cpu: 4
      memory: 8G
    download_ccache_script:
      - bash download_ccache
    sync_script:
      - bash sync
    #build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache
#start build 

