#!/bin/bash

url=https://m.mark41stark.workers.dev/0://SyASx.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf SyASx.gz
echo "unzip done"
find SyASx.gz -delete
